Ext.define('Atlas.model.Program', {
  extend: 'Ext.data.Model',
  fields: [{
    name: 'id',
    type: 'int'
  }, {
    name: 'name',
    type: 'string'
  }, {
    name: 'type',
    type: 'string'
  }, {
    name: 'atlas_registration_type',
    type: 'string'
  }, {
    name: 'disabled',
    type: 'int'
  }, {
    name: 'queue_category_id',
    type: 'int'
  }, {
    name: 'approval_required',
    type: 'int'
  }, {
    name: 'form_esign_required',
    type: 'int'
  }, {
    name: 'confirmation_id_length',
    type: 'int'
  }, {
    name: 'response_expires_in',
    type: 'int'
  }, {
    name: 'created',
    type: 'date',
    dateFormat: 'Y-m-d H:i:s'
  }, {
    name: 'modified',
    type: 'date',
    dateFormat: 'Y-m-d H:i:s'
  }, {
    name: 'expires',
    type: 'date',
    dateFormat: 'Y-m-d H:i:s'
  }],
  associations: [{
    type: 'hasMany',
    model: 'ProgramStep',
    name: 'program_steps'
  }, {
    type: 'hasMany',
    model: 'ProgramResponse',
    name: 'program_responses'
  }, {
    type: 'hasMany',
    model: 'ProgramEmail',
    name: 'program_emails'
  }, {
    type: 'hasMany',
    model: 'ProgramDocument',
    name: 'program_documents'
  },  {
    type: 'hasMany',
    model: 'ProgramInstruction',
    name: 'program_instructions'
  }, {
    type: 'hasMany',
    model: 'WatchedFilingCat',
    name: 'watched_filing_cats'
  }]
});
